using System;
using System.Collections.Generic;
using System.Text;

namespace DBDStatBot.Models
{
    ///< summary >
    /// Enum that's used to filter out unwanted or ununcessary stat categories from the Steam API.
    /// </ summary >
    public enum StatFilterEnum
    {
        //DBD_KillerSkulls,
        //DBD_SacrificedCampers,
        //DBD_TrapPickup,
        //DBD_GeneratorPct_float,
        //DBD_HealPct_float,
        //DBD_SacrificedCampers_iam,
        //DBD_BloodwebMaxLevel,
        //DBD_BloodwebPoints,
        //DBD_PerksCount_Idx0,
        //DBD_PerksCount_Idx1,
        //DBD_PerksCount_Idx2,
        //DBD_PerksCount_Idx3,
        //DBD_PerksCount_Idx268435456,
        //DBD_PerksCount_Idx268435457,
        //DBD_PerksCount_Idx268435458,
        //DBD_BloodwebPerkMaxLevel,
        //DBD_MaxBloodwebPointsOneCategory,
        //DBD_CamperFullLoadout,
        //DBD_CamperNewItem,
        //DBD_CamperEscapeWithItemFrom,
        //DBD_UnlockRanking,
        //DBD_FixSecondFloorGenerator_MapAsy_Asylum,
        //DBD_SlasherChainAttack,
        //DBD_FixSecondFloorGenerator_MapSub_Street,
        //DBD_FixSecondFloorGenerator_MapSwp_PaleRose,
        //DBD_DLC3_Camper_Stat1,
        //DBD_HitNearHook,
        //DBD_Camper8_Stat1,
        //DBD_Camper8_Stat2,
        //DBD_Camper9_Stat2,
        //DBD_DLC5_Slasher_Stat1,
        //DBD_DLC6_Slasher_Stat2,
        //DBD_DLC7_Camper_Stat1,
        //DBD_DLC7_Camper_Stat2,
        //DBD_DLC8_Slasher_Stat2,
        //DBD_DLC8_Camper_Stat1,
        //DBD_Event1_Stat2,
        //DBD_Event1_Stat3,
        //DBD_DLC9_Slasher_Stat1,
        //DBD_DLC9_Camper_Stat1,
        //DBD_Chapter9_Slasher_Stat1,
        //DBD_Chapter10_Camper_Stat1,
        //DBD_FixSecondFloorGenerator_MapKny_Cottage,
        //DBD_Chapter11_Camper_Stat1_float,
        //DBD_Chapter12_Camper_Stat1,
        //DBD_DLC4_Slasher_Stat1,
        //DBD_DLC4_Slasher_Stat2,
        //DBD_SlasherTierIncrement,
        //DBD_BloodwebPrestige3MaxLevel,
        //DBD_BloodwebMaxPrestigeLevel,
        //DBD_CamperMaxScoreByCategory,
        //DBD_SlasherMaxScoreByCategory,
        //DBD_KilledCampers_iam,
        //DBD_EscapeNoBlood_MapAsy_Asylum,
        //DBD_FixSecondFloorGenerator_MapBrl_MaHouse,
        //DBD_DLC6_Slasher_Stat1,
        //DBD_DLC7_Slasher_Stat1,
        //DBD_DLC7_Slasher_Stat2,
        //DBD_FinishWithPerks_Idx11,
        //DBD_FixSecondFloorGenerator_MapFin_Hideout,
        //DBD_FixSecondFloorGenerator_MapAsy_Chapel,
        DBD_SkillCheckSuccess,
        DBD_Escape,
        DBD_BloodwebPoints,
        DBD_EscapeThroughHatch,
        DBD_HitNearHook
    }
}
